export type Product={slug:string;name:string;meta:string;price:number;tone:'white'|'red'|'barca'|'black'|'gold';badge?:string;mark:string;category:string;club?:string;player?:string;signed?:boolean;description:string;sizes?:string[]};

export const products:Product[]=[
{slug:'real-madrid-home-2025-26',name:'Real Madrid Home Jersey',meta:'2025/26 • Player Edition',price:129,tone:'white',badge:'NEW',mark:'RM',category:'Shirts',club:'Real Madrid',description:'Premium replica jersey inspired by the current Real Madrid home collection.',sizes:['S','M','L','XL']},
{slug:'barcelona-home-2025-26',name:'FC Barcelona Home Jersey',meta:'2025/26 • Stadium',price:119,tone:'barca',badge:'HOT',mark:'FCB',category:'Shirts',club:'Barcelona',description:'Modern blaugrana home jersey with a classic football silhouette.',sizes:['S','M','L','XL']},
{slug:'liverpool-home-2025-26',name:'Liverpool Home Jersey',meta:'2025/26 • Authentic',price:139,tone:'red',badge:'NEW',mark:'LFC',category:'Shirts',club:'Liverpool',description:'Premium Liverpool-inspired home jersey for collectors and fans.',sizes:['S','M','L','XL']},
{slug:'germany-home-2025',name:'Germany Home Jersey',meta:'2025 • DFB Edition',price:109,tone:'white',badge:'ICON',mark:'GER',category:'Shirts',club:'Germany',description:'Germany national-team inspired jersey for the modern collector.',sizes:['S','M','L']},
{slug:'retro-bayern-1999',name:'Bayern Retro Jersey',meta:'1999 • Heritage Collection',price:159,tone:'red',badge:'RETRO',mark:'FCB',category:'Shirts',club:'Bayern',description:'A retro-inspired Bayern collector piece with classic styling.',sizes:['M','L','XL']},
{slug:'black-training-top',name:'Elite Black Training Top',meta:'Performance • 2026',price:89,tone:'black',badge:'LIMITED',mark:'MA',category:'Shirts',description:'Minimal premium training top with a modern athletic cut.',sizes:['S','M','L','XL']},
{slug:'messi-signed-argentina-jersey',name:'Lionel Messi Signed Argentina Jersey',meta:'Signed • Certificate',price:0,tone:'white',badge:'SIGNED',mark:'10',category:'Shirts',player:'Lionel Messi',club:'Argentina',signed:true,description:'Example listing for a signed Argentina jersey with certificate and provenance record.'}
];
