export type Product={slug:string;name:string;meta:string;price:number;tone:'white'|'red'|'barca'|'black'|'gold';badge?:string;mark:string;category:string;club?:string;player?:string;signed?:boolean;description:string;sizes?:string[]};
export const products:Product[]=[
{slug:'real-madrid-home-2025-26',name:'Real Madrid Home Jersey',meta:'2025/26 • Player Edition',price:129,tone:'white',badge:'NEW',mark:'RM',category:'Jerseys',club:'Real Madrid',description:'Premium replica jersey inspired by the current Real Madrid home collection.',sizes:['S','M','L','XL']},
{slug:'barcelona-home-2025-26',name:'FC Barcelona Home Jersey',meta:'2025/26 • Stadium',price:119,tone:'barca',badge:'HOT',mark:'FCB',category:'Jerseys',club:'Barcelona',description:'Modern blaugrana home jersey with a classic football silhouette.',sizes:['S','M','L','XL']},
{slug:'liverpool-home-2025-26',name:'Liverpool Home Jersey',meta:'2025/26 • Authentic',price:139,tone:'red',badge:'NEW',mark:'LFC',category:'Jerseys',club:'Liverpool',description:'Premium Liverpool-inspired home jersey for collectors and fans.',sizes:['S','M','L','XL']},
{slug:'germany-home-2025',name:'Germany Home Jersey',meta:'2025 • DFB Edition',price:109,tone:'white',badge:'ICON',mark:'GER',category:'Jerseys',club:'Germany',description:'Germany national-team inspired jersey for the modern collector.',sizes:['S','M','L']},
{slug:'retro-bayern-1999',name:'Bayern Retro Jersey',meta:'1999 • Heritage Collection',price:159,tone:'red',badge:'RETRO',mark:'FCB',category:'Retro',club:'Bayern',description:'A retro-inspired Bayern collector piece with classic styling.',sizes:['M','L','XL']},
{slug:'black-training-top',name:'Elite Black Training Top',meta:'Performance • 2026',price:89,tone:'black',badge:'LIMITED',mark:'MA',category:'Training',description:'Minimal premium training top with a modern athletic cut.',sizes:['S','M','L','XL']},
{slug:'gold-collector-scarf',name:'Legends Collector Scarf',meta:'Limited • Numbered',price:79,tone:'gold',badge:'LIMITED',mark:'XI',category:'Accessories',description:'Numbered collector scarf for the premium football archive.'},
{slug:'messi-signed-argentina-jersey',name:'Lionel Messi Signed Argentina Jersey',meta:'Signed • Certificate',price:0,tone:'white',badge:'SIGNED',mark:'10',category:'Signed',player:'Lionel Messi',club:'Argentina',signed:true,description:'Example listing for a signed Argentina jersey with certificate and provenance record.'}
];
export type Auction={slug:string;player:string;item:string;bid:number;endsAt:string;tone:'arg'|'port'|'france'|'brazil';mark:string;bids:number;signed:boolean;description:string};
export const auctions:Auction[]=[
{slug:'messi-signed-argentina-jersey',player:'Lionel Messi',item:'Signed Argentina Jersey',bid:1250,endsAt:'2026-09-16T12:30:00+02:00',tone:'arg',mark:'10',bids:18,signed:true,description:'Featured signed Argentina jersey listing with certificate and signing-proof area.'},
{slug:'ronaldo-signed-portugal-jersey',player:'Cristiano Ronaldo',item:'Signed Portugal Jersey',bid:980,endsAt:'2026-09-15T06:12:00+02:00',tone:'port',mark:'7',bids:13,signed:true,description:'Featured signed Portugal jersey listing with a provenance panel.'},
{slug:'zidane-signed-france-jersey',player:'Zinedine Zidane',item:'Signed France Jersey',bid:1850,endsAt:'2026-09-17T10:22:00+02:00',tone:'france',mark:'10',bids:21,signed:true,description:'Premium legend-piece listing for a signed France jersey.'},
{slug:'pele-signed-brazil-jersey',player:'Pelé',item:'Signed Brazil Jersey',bid:2500,endsAt:'2026-09-19T19:30:00+02:00',tone:'brazil',mark:'10',bids:31,signed:true,description:'Historic signed Brazil jersey listing.'}
];
